sudo: required

language: cpp
compiler: gcc
dist: trusty

install:
        - sudo apt-get install -y pkg-config libx11-dev libxcursor-dev        
script:
        - BUILD_DSSI=true BUILD_VST2=true BUILD_LV2=true BUILD_JACK=true make
